In [2]:
import numpy as np
#single dimentional numpy array
n1 = np.array([10, 20, 30, 40, 50])
type(n1)

numpy.ndarray

In [9]:
#mutidimentional
n2 = np.array([[1, 2, 3, 4, 5], [11, 22, 33, 44, 55]])
n2

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [12]:
n0 = np.zeros((4,5))
n0

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
n10 = np.full((3,3),10)
n10

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [16]:
na = np.arange(10,50,5)
nb = np.arange(7,16)
print(na)
nb

[10 15 20 25 30 35 40 45]


array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
nr = np.random.randint(100,200,7)
nr

array([179, 132, 149, 199, 103, 105, 151])

In [20]:
n1.shape

(5,)

In [21]:
n2.shape

(2, 5)

In [22]:
n2.shape = (5,2)
n2

array([[ 1,  2],
       [ 3,  4],
       [ 5, 11],
       [22, 33],
       [44, 55]])

In [23]:
ni = np.array([10,20])
nj = np.array([30,40])
np.sum((ni,nj))

100

In [24]:
np.sum([ni,nj],axis=0)

array([40, 60])

In [25]:
np.sum([ni,nj],axis=1)

array([30, 70])

In [26]:
a = np.array([10,20,30])
b = np.array([40,50,60])
np.vstack((a,b))

array([[10, 20, 30],
       [40, 50, 60]])

In [27]:
np.hstack((a,b))

array([10, 20, 30, 40, 50, 60])

In [29]:
np.column_stack((a,b))

array([[10, 40],
       [20, 50],
       [30, 60]])